/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AvgCheckByCategory: typeof import('./src/components/charts/orders/AvgCheckByCategory.vue')['default']
    AvgCheckByCategoryBarChart: typeof import('./src/components/charts/orders/AvgCheckByCategoryBarChart.vue')['default']
    AvgCheckByCategoryChart: typeof import('./src/components/charts/orders/AvgCheckByCategoryChart.vue')['default']
    'BarСhart': typeof import('./src/components/charts/incomes/BarСhart.vue')['default']
    Button: typeof import('primevue/button')['default']
    CategoryDoughnutChart: typeof import('./src/components/charts/stocks/CategoryDoughnutChart.vue')['default']
    Chart: typeof import('primevue/chart')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Drawer: typeof import('primevue/drawer')['default']
    'DynamicsOfGoodsReceiptBarСhart': typeof import('./src/components/charts/incomes/DynamicsOfGoodsReceiptBarСhart.vue')['default']
    'GoodsReceiptBarСhart': typeof import('./src/components/charts/incomes/GoodsReceiptBarСhart.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IncomesChart: typeof import('./src/components/charts/IncomesChart.vue')['default']
    'IncomesGroupedByDateBarСhart': typeof import('./src/components/charts/incomes/IncomesGroupedByDateBarСhart.vue')['default']
    'IncomesGroupedByDateСhart': typeof import('./src/components/charts/incomes/IncomesGroupedByDateСhart.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    PriceDiscountScatterChart: typeof import('./src/components/charts/sales/PriceDiscountScatterChart.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesTrendLineChart: typeof import('./src/components/charts/sales/SalesTrendLineChart.vue')['default']
    Select: typeof import('primevue/select')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Slider: typeof import('primevue/slider')['default']
    Tag: typeof import('primevue/tag')['default']
    TopBrandsBarChart: typeof import('./src/components/charts/orders/TopBrandsBarChart.vue')['default']
    TopBrandsByRevenuePieChart: typeof import('./src/components/charts/orders/TopBrandsByRevenuePieChart.vue')['default']
    TopBrandsChart: typeof import('./src/components/charts/orders/TopBrandsChart.vue')['default']
    TopBrandsPieChart: typeof import('./src/components/charts/orders/TopBrandsPieChart.vue')['default']
    TopProductsBarChart: typeof import('./src/components/charts/incomes/TopProductsBarChart.vue')['default']
    TopProductsByQuantityOfDeliveriesBarChart: typeof import('./src/components/charts/incomes/TopProductsByQuantityOfDeliveriesBarChart.vue')['default']
    TopProductsByQuantityOfDeliversBarChart: typeof import('./src/components/charts/incomes/TopProductsByQuantityOfDeliversBarChart.vue')['default']
    TopProductsChart: typeof import('./src/components/charts/incomes/TopProductsChart.vue')['default']
    TopProductsDeliversBarChart: typeof import('./src/components/charts/incomes/TopProductsDeliversBarChart.vue')['default']
    WarehousesStockBarChart: typeof import('./src/components/charts/stocks/WarehousesStockBarChart.vue')['default']
    WarehousesStockChart: typeof import('./src/components/charts/stocks/WarehousesStockChart.vue')['default']
  }
}
