/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AvgCheckByCategoryBarChart: typeof import('./src/components/charts/orders/AvgCheckByCategoryBarChart.vue')['default']
    Button: typeof import('primevue/button')['default']
    CategoryDoughnutChart: typeof import('./src/components/charts/stocks/CategoryDoughnutChart.vue')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Drawer: typeof import('primevue/drawer')['default']
    'GoodsReceiptBarСhart': typeof import('./src/components/charts/incomes/GoodsReceiptBarСhart.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    PriceDiscountScatterChart: typeof import('./src/components/charts/sales/PriceDiscountScatterChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesTrendLineChart: typeof import('./src/components/charts/sales/SalesTrendLineChart.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    TopBrandsBarChart: typeof import('./src/components/charts/orders/TopBrandsBarChart.vue')['default']
    TopBrandsByRevenuePieChart: typeof import('./src/components/charts/orders/TopBrandsByRevenuePieChart.vue')['default']
    TopProductsByQuantityOfDeliveriesBarChart: typeof import('./src/components/charts/incomes/TopProductsByQuantityOfDeliveriesBarChart.vue')['default']
    WarehousesStockBarChart: typeof import('./src/components/charts/stocks/WarehousesStockBarChart.vue')['default']
  }
}
